version: 2.1

jobs:

  git_commits:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Install pytest
          command: make install
      - run:
          name: Test git commits
          command: make test

  spelling:
    docker:
      - image: tmaier/markdown-spellcheck:latest
    steps:
      - checkout
      - run:
          name: Check spelling
          command: mdspell --report --ignore-numbers --ignore-acronyms "**/*.md"

  markdownlint:
    docker:
      - image: tmknom/markdownlint:0.33.0
    steps:
      - checkout

      # Note, we can't use a make target here as `make` isn't installed on this Docker image.
      - run:
          name: Lint content with markdownlint
          command: markdownlint .

  prettier:
    docker:
      # See https://hub.docker.com/r/tmknom/prettier/tags for available tags.
      - image: tmknom/prettier:3.2.5
    steps:
      - checkout
      - run:
          name: Check Prettier
          command: prettier --check --parser=markdown .

workflows:
  static-analysis:
    jobs:
      - git_commits
      - spelling
      - markdownlint
      - prettier
